### ISSUE TITLE
Cant enter 10.00

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [benhurott/react-native-masked-text#24] opened 2017-05-21 15:45 UTC
When trying to enter $10 the zeros don't get added.

**Comment by benhurott** [comment] 2017-05-22 12:43
Hi,

Can you paste the code here?

**Comment by imanodaysoffdotcom** [comment] 2017-05-22 15:00
import React, { Component } from 'react';
import { Image, Dimensions, Linking, KeyboardAvoidingView } from 'react-native';
import { Container, Content, Card, CardItem, Text, View, InputGroup, Input, Button } from 'native-base';
import {TextInputMask} from 'react-native-masked-text';
import Parse from 'parse/react-native';
import { connect } from 'react-redux';
const window = Dimensions.get('window');
import styles from './styles';
import JustGiveInputView from './JustGiveInputView';
var heightOfImageContainer = 0;
var widthOfImageContainer = 0;
var {height, width} = Dimensions.get('window');

class JustGive extends Component { // eslint-disable-line

  constructor(props) {
    super(props);
    this.state = {
      selectedItem: undefined,
      selectedTab: 0,
      titheTotal: "0.00",
      hashTag: '',
      behaviorModals: 'position'
    };

    this.submitButtonClicked = this.submitButtonClicked.bind(this);

  }

   onChangeText(amount) {
     console.log("text");
     console.log("Setting state for value change " + amount);
     this.setState({paymentAmount:amount})
   }

  render() { // eslint-disable-line
    return (

      <View style={{flex: 1, backgroundColor: 'transparent'}}>

        <View style={{flex: 1, backgroundColor: 'transparent'}} onLayout={(event) => {
            var {x, y, width, height} = event.nativeEvent.layout;
            heightOfImageContainer = height;
            widthOfImageContainer = width;
          }}>
            <Image style={{flex: 1, width: null, height: heightOfImageContainer, marginTop: 20}} resizeMode={'contain'} source={require('../../../img/justgiveThankyou.png')} />
        </View>
        <View style={{flex: 0.75,  flexDirection: 'column', justifyContent: 'space-between',marginTop: 10, marginBottom: 15, marginHorizontal: 10}}>
            <View style={{flex: 1, borderRadius: 10, marginTop: 5, backgroundColor: '#390063', flexDirection: 'row'}}>
              <Text style={{flex: 1, color: 'white', marginLeft: 15, alignSelf:'center'}}>Enter Amount Here</Text>
              <View style={{flex: 0.65, height:35, alignSelf:'center', justifyContent:'center', marginRight: 10, backgroundColor: 'white', borderRadius: 10}}>
                <TextInputMask ref={'paymentAmount'} value={this.state.paymentAmount} onChangeText={this.onChangeText.bind(this)} style={{flex:1, marginHorizontal: 10}} type={'money'} options={{ unit: '$', separator: '.', delimiter: ',' }} />
              </View>
            </View>
            <View style={{flex: 1, borderRadius: 10, marginTop: 5, backgroundColor: '#390063', flexDirection: 'row'}}>
              <Text style={{flex: 1, color: 'white', marginLeft: 15, alignSelf:'center'}}>Hashtag (Optional)</Text>
              <View style={{flex: 0.65, height:35, alignSelf:'center', marginRight: 10, backgroundColor: 'white', borderRadius: 10}}>
                <InputGroup style={{flex: 0.5, alignSelf:'center', textAlign:'center'}} borderType='rounded' >
                              <Input ref={'hashtag'} onChangeText={(hastagvalue) => this.setState({hashtag:hastagvalue})} keyboardType={'alpha'} placeholder=''/>
                </InputGroup>
              </View>
            </View>
        </View>

        <View style={{flex: 0.45, backgroundColor: '#FF8162', flexDirection: 'column', justifyContent: 'center'}} onLayout={(event) => {
            var {x, y, width, height} = event.nativeEvent.layout;
            heightOfSubmitContainer = height;
          }}>
          <View style={{flex: 1, backgroundColor: 'transparent', flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end',}}>
            <Button ref="paymentButton" onPress={() => {this.submitButtonClicked()}} color="white" style={{width:100, height: 35, backgroundColor: '#390063', marginRight: 20, alignSelf: 'center'}}>Submit</Button>
          </View>
        </View>

      </View>

    );
  }
}

**Comment by benhurott** [comment] 2017-05-22 16:43
I can't reproduce this.

Look to this sample:

![mask_working mov](https://cloud.githubusercontent.com/assets/3187772/26319223/86ac6c12-3ef4-11e7-9f03-7c51798ea761.gif)

Has some errors on console?
Can you send me prints of the state?

**Comment by imanodaysoffdotcom** [comment] 2017-05-22 18:05
Please try to type in Ten dollars or maybe even 100.00.

**Comment by imanodaysoffdotcom** [comment] 2017-05-22 18:06
The erros is only when trying to add trailing zero's consecutively. For example 10000 which should be 10,000 but instead only 0.01 shows up

**Comment by benhurott** [comment] 2017-05-22 19:42
Can you send me a gif or video reproducing this error?

![money_mask_trailling mov](https://cloud.githubusercontent.com/assets/3187772/26325487/7562ee40-3f0d-11e7-9d75-7d775796bb5a.gif)

I realy can't reproduce this here =/

**Comment by imanodaysoffdotcom** [comment] 2017-05-23 00:34
Sorry, i got it working. Thanks for your prompt response

**Comment by benhurott** [comment] 2017-05-23 01:13
Ok,

I will close this for now =).

**Closed by benhurott** 2017-05-23 01:13 UTC
Labels: more information needed

**Comment by masiamj** [comment] 2017-10-17 17:06
I'm actually encountering this same error. @imanodaysoffdotcom How did you end up resolving?

**Comment by imanodaysoffdotcom** [comment] 2017-10-20 17:15
Been a while so i dont remember so i will just show you some code to see if
it helps


<TextInputMask ref={'paymentAmount'} value={this.state.paymentAmount}
onChangeText={this.onChangeText.bind(this)} style={{flex:1,
marginHorizontal: 10}} type={'money'} options={{ unit: '$', separator: '.',
delimiter: ',' }} />


onChangeText(amount) {
     console.log("text");
     console.log("Setting state for value change " + amount);
     this.setState({paymentAmount:amount})
   }
